# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
LiveKit connector orchestrator.

Manages the full lifecycle of the LiveKit transport:
  1. Starts the LiveKit server Docker container.
  2. Optionally starts the browser-facing token server (only needed when clients
     are on HTTPS and cannot connect to the LiveKit WS directly).
  3. Registers this process as a ConnectorEndpoint with the DeviceIOHub IPC layer.
  4. Connects the Python room client to the LiveKit room.
  5. Runs the IPC return-traffic loop and the room client concurrently.

Token server is opt-in via LiveKitConnectorConfig.enable_token_server (default False).
On a local/HTTP network clients can connect directly to ws://<host>:7880 using a
token generated by livekit-api — no proxy needed.

Usage
-----
    cfg = LiveKitConnectorConfig(
        api_key="...",
        api_secret="...",
        room_name="my-room",
    )
    conn = LiveKitConnector(cfg)
    await conn.start()
    try:
        await conn.run()
    finally:
        await conn.stop()
"""
from __future__ import annotations

import asyncio
from contextlib import AsyncExitStack
from typing import Awaitable, Callable

from loguru import logger

from device_io_hub._errors import StartupError
from device_io_hub.ipc import (
    AudioChunk,
    ConnectorEndpoint,
    DataMessage,
)
from device_io_hub.ipc._connector import _ConnectorRegistrationError

from ._docker import LiveKitDocker
from ._hwcodec import require_nvidia_video_codecs
from ._room_client import RoomClient
from ._token_server import TokenServer
from ._web_server import WebServer
from .config import LiveKitConnectorConfig

ReturnAudioCallback = Callable[[AudioChunk],  Awaitable[None]]
ReturnDataCallback  = Callable[[DataMessage], Awaitable[None]]


# Leave 15 s for Docker stop/reaping and 1 s of margin inside the launcher's
# 20 s shutdown window. Room, web, and token cleanup share this budget.
_CLIENT_CLEANUP_TIMEOUT_S = 4.0


class LiveKitConnector:
    def __init__(self, cfg: LiveKitConnectorConfig) -> None:
        self._cfg    = cfg
        self._docker = LiveKitDocker(self._cfg)
        self._token  = TokenServer(self._cfg) if self._cfg.enable_token_server else None
        self._web    = WebServer(self._cfg)    if self._cfg.enable_web_server   else None
        self._ep     = ConnectorEndpoint(
            push_addr=self._cfg.hub_push_addr,
            sub_addr=self._cfg.hub_sub_addr,
            num_slots=self._cfg.shm_num_slots,
            max_frame_bytes=self._cfg.shm_max_frame_bytes,
            file_push_addr=self._cfg.hub_file_push_addr,
            file_hwm=self._cfg.incoming_file_ipc_hwm,
            file_max_bytes=self._cfg.incoming_file_max_bytes,
        )
        self._room_client = RoomClient(self._cfg, self._ep)
        self._room_connect_started = False

    # ── callback registration ─────────────────────────────────────────────────

    def on_return_audio(self, cb: ReturnAudioCallback) -> None:
        """Called when the hub sends TTS/agent audio back to a participant."""
        self._ep.on_return_audio(cb)

    def on_return_data(self, cb: ReturnDataCallback) -> None:
        """Called when the hub sends agent text/binary back to a participant."""
        self._ep.on_return_data(cb)

    # ── lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        """Start Docker, optional servers, register IPC endpoint, connect room client.

        Any startup failure triggers cleanup of owned resources. Cleanup errors
        are logged without replacing the startup failure.

        Raises
        ------
        RuntimeError
            If shared-memory registration fails or a startup prerequisite is
            not met. Operator-facing failures include a diagnostic banner.
        """
        try:
            require_nvidia_video_codecs()
            await self._docker.start()
            if self._token:
                await self._token.start()
            if self._web:
                await self._web.start()
            # Ring creation happens inside register(), after the expensive
            # services above and immediately before the IPC handshake.
            await self._ep.register()
            self._room_connect_started = True
            await self._room_client.connect()
            self._ep.on_return_data(self._room_client.send_return_data)
            self._ep.on_return_audio(self._room_client.send_return_audio)
            self._ep.on_return_audio_flush(self._room_client.flush_return_audio)
            self._ep.on_return_video(self._room_client.send_return_video)
            self._ep.on_return_video_stop(self._room_client.stop_return_video)
            logger.info("LiveKitConnector started — room={!r}", self._cfg.room_name)
        except BaseException as exc:
            try:
                await self.stop()
            except (Exception, asyncio.CancelledError):
                logger.exception("LiveKitConnector cleanup failed after startup failure")
            if isinstance(exc, _ConnectorRegistrationError):
                banner = "━" * 56
                raise StartupError("\n".join([
                    "",
                    banner,
                    "  DeviceIOHub video IPC registration failed — refusing to start",
                    banner,
                    "  LiveKit media was not accepted.",
                    f"  {exc}",
                    banner,
                ])) from exc
            raise

    async def run(self) -> None:
        """
        Run IPC return-traffic loop and room client concurrently.

        Returns when stop() is called or either task raises an unhandled exception.
        """
        ipc_task  = asyncio.create_task(self._ep.run(),          name="ipc-return")
        room_task = asyncio.create_task(self._room_client.run(), name="room-client")
        try:
            done, pending = await asyncio.wait(
                [ipc_task, room_task],
                return_when=asyncio.FIRST_EXCEPTION,
            )
        except asyncio.CancelledError:
            ipc_task.cancel()
            room_task.cancel()
            await asyncio.gather(ipc_task, room_task, return_exceptions=True)
            raise

        for t in pending:
            t.cancel()
        await asyncio.gather(*pending, return_exceptions=True)

        for t in done:
            exc = t.exception()
            if exc:
                logger.error("Connector task {!r} raised: {}", t.get_name(), exc)

    async def stop(self) -> None:
        """Shut down all components, attempting every cleanup even if one fails.

        Cleanup errors propagate after every cleanup step has been attempted.
        """
        logger.info("LiveKitConnector stopping…")
        deadline = asyncio.get_running_loop().time() + _CLIENT_CLEANUP_TIMEOUT_S

        async def stop_client(callback: Callable[[], Awaitable[None]]) -> None:
            async with asyncio.timeout_at(deadline):
                await callback()

        async with AsyncExitStack() as server_cleanup, AsyncExitStack() as cleanup:
            # The outer stack retains client errors as exception context.
            # Registered first, executed last: keep LiveKit available until
            # media cleanup and room disconnection have finished.
            server_cleanup.push_async_callback(self._docker.stop)
            if self._token:
                cleanup.push_async_callback(stop_client, self._token.stop)
            if self._web:
                cleanup.push_async_callback(stop_client, self._web.stop)
            cleanup.callback(self._ep.close)
            if self._room_connect_started:
                self._room_connect_started = False
                cleanup.push_async_callback(stop_client, self._room_client.disconnect)
            cleanup.callback(self._room_client.stop)
            cleanup.callback(self._ep.stop)
        logger.info("LiveKitConnector stopped")
